### ISSUE TITLE
Operator instanceOf support

### ISSUE THREAD

**Issue by Epsil0neR** [kogarashisan/ClassManager#1]
Привет из хабрахабра!
Думаю поддержку такого важного оператора как "instanceOf" добавить не составит труда. Скажем есть классы Animal и Cat(extends Animal), почему бы перед копированием методов и свойств из класса Animal в класс Cat и созданием новых методов и свойств в классе Cat не сделать так: "Cat.prototype = Object.create(Animal.prototype)", в таком случае:
var myCat = new Cat();
console.info(myCat instanceOf Animal); //Выведет true

А использоваться Animal как прототип будет оператором instanceOf и других крайних случаях.

**Comment by kogarashisan** [comment]
Это, извиняюсь, провтыкал. Добавил в сборку Lava.instanceOf:

```
var cat = new Cat();
Lava.instanceOf(cat, "global.Animal")
```

Так устроит?

**Comment by Epsil0neR** [comment]
лучше всего использовать оператор чем использовать костыль. Ведь если ты объявишь прототипу Cat протипом Animal и потом скопируешь всё из Animal.prototype в Cat.prototype, то тогда оператор instanceOf будет работать, но будут использоваться только функции из Cat.prototype

**Comment by kogarashisan** [comment]
Я сильно против этого. Во-первых, то, что вы называете "костылем" - это предлагаемый мной способ решить вашу задачу. И он ничем не хуже оператора.

Во-вторых: если посмотрите на исходник фреймворка LiquidLava - то там эта функция не используется совсем. В документации я учу людей, что если программа типизирована, то он не понадобится. А для того, чтобы отличать основные классы - в них есть константы isProperties, isObservable и так далее.

Я подумаю над вашим предложением, но сперва мне нужно убедиться что это 
1) не повлияет на возможность патчинга методов
2) не повлияет на производительность (самое сложное!)
3) не будет конфликтовать с возможностями пропатчить классы до их загрузки и генерацией их на сервере...

**Comment by kogarashisan** [comment]
Закрываю по простой причине: нет решаемой задачи.
