### ISSUE TITLE
Error: Class is already defined: global.LavaPerson

### ISSUE THREAD

**Issue by Josema** [kogarashisan/ClassManager#2]
Uncaught Error: Class is already defined: global.LavaPerson.
message: Uncaught Error: Class is already defined: global.LavaPerson

Can you tell me why this is happening?

**Comment by kogarashisan** [comment]
1) After you define a class for the first time - it's cached in ClassManager.
For example: 

```
Lava.define( 'Lava.view.Foreach', ...)
```

This will generate a constructor and put it under it's namespace peth:

```
// near-equivalent code
window.Lava.view.Foreach = function() {...}
```

It will also be stored in 

```
Lava.ClassManager._sources["Lava.view.Foreach"] // object with internal class data
Lava.ClassManager.constructors["Lava.view.Foreach"] // constructor
```

2) You can not define same class again - there is no adequate reason to do so. If this was allowed to happen - then previous class with all associated data would be overwritten. 

In real applications this could happen if you accidentially included file with class sources twice, or there is a name conflict. So this error protects you from such accidents.

3) Probably you see this cause you put class generation into "test" section on JSPerf. Why would you want to do it? 

Normally, class generation should reside in preparation section, before all tests, so it's run only once.

If you want to measure time of class generation - you can manually assign empty object into `Lava.ClassManager._sources` and null into class name after you generated the class.
